using Npgsql;
using System.Runtime.CompilerServices;

namespace PgLib2.Objects.Query;

internal class PgColumnQuery
{
    internal static SQLSet GenerateSQLSet()
        => new SQLSet(SQL, new NpgsqlParameter[]
        {
            new NpgsqlParameter("table_oid", NpgsqlTypes.NpgsqlDbType.Oid)
        });
    private static readonly string SQL = @"SELECT DISTINCT ON (c.oid, a.attnum)
 c.oid AS table_oid
,nc.nspname AS table_schema
,c.relname AS table_name
,a.attname AS column_name
,col_description(a.attrelid, a.attnum) AS comment
,a.attnum AS ordinal_position
,NOT t.typcategory IN('N', 'B') AS need_quote
,a.attnotnull OR (t.typtype = 'd' AND t.typnotnull) AS is_not_null
,CASE WHEN a.attgenerated = '' THEN pg_get_expr(ad.adbin, ad.adrelid) ELSE NULL END AS column_default
,CASE
    WHEN a.attidentity = 'a' THEN format_type(a.atttypid, NULL) || ' GENERATED ALWAYS AS IDENTITY'
    WHEN a.attidentity = 'd' THEN format_type(a.atttypid, NULL) || ' GENERATED BY DEFAULT AS IDENTITY'
    WHEN seq.seqrelid IS NOT NULL AND a.attidentity = '' AND format_type(a.atttypid, NULL) = 'integer' THEN 'serial'
    WHEN seq.seqrelid IS NOT NULL AND a.attidentity = '' AND format_type(a.atttypid, NULL) = 'bigint' THEN 'bigserial'
    WHEN seq.seqrelid IS NOT NULL AND a.attidentity = '' AND format_type(a.atttypid, NULL) = 'smallint' THEN 'smallserial'
    WHEN a.attgenerated = '' AND pg_get_expr(ad.adbin, ad.adrelid) ~ 'nextval\(''\w+''::regclass\)' THEN 'serial'
    ELSE COALESCE(type_map.dst, dt.raw_data_type)
 END AS data_type
,information_schema._pg_char_max_length(information_schema._pg_truetypid(a.*, t.*),information_schema._pg_truetypmod(a.*, t.*)) AS character_maximum_length
,information_schema._pg_numeric_precision(information_schema._pg_truetypid(a.*, t.*),information_schema._pg_truetypmod(a.*, t.*)) AS numeric_precision
,information_schema._pg_numeric_scale(information_schema._pg_truetypid(a.*, t.*),information_schema._pg_truetypmod(a.*, t.*)) AS numeric_scale
,information_schema._pg_datetime_precision(information_schema._pg_truetypid(a.*, t.*),information_schema._pg_truetypmod(a.*, t.*)) AS datetime_precision
,(c.relkind IN ('r', 'p') OR (c.relkind IN ('v', 'f') AND pg_column_is_updatable(c.oid::regclass, a.attnum, false))) AS is_updatable
FROM
 pg_attribute a
LEFT OUTER JOIN pg_attrdef ad ON (a.attrelid = ad.adrelid AND a.attnum = ad.adnum)
INNER JOIN pg_class c ON (a.attrelid = c.oid)
INNER JOIN pg_namespace nc ON (c.relnamespace = nc.oid)
INNER JOIN pg_type t ON (a.atttypid = t.oid)
INNER JOIN pg_namespace nt ON (t.typnamespace = nt.oid)
LEFT OUTER JOIN pg_type bt ON (t.typtype = 'd' AND t.typbasetype = bt.oid)
LEFT OUTER JOIN pg_namespace nbt ON (bt.typnamespace = nbt.oid)
LEFT OUTER JOIN pg_depend dep ON (
  dep.refclassid = 'pg_class'::regclass
  AND dep.refobjid  = c.oid
  AND dep.refobjsubid = a.attnum
  AND dep.classid = 'pg_class'::regclass
  AND dep.deptype IN ('a','i')
)
LEFT JOIN pg_sequence seq ON (dep.objid = seq.seqrelid)
CROSS JOIN LATERAL (
    SELECT
      CASE WHEN t.typtype = 'd' THEN
          CASE WHEN bt.typelem <> 0 AND bt.typlen = -1 THEN 'ARRAY'
               WHEN nbt.nspname = 'pg_catalog' THEN format_type(t.typbasetype, NULL)
               ELSE 'USER-DEFINED' END
      ELSE
          CASE WHEN t.typelem <> 0 AND t.typlen = -1 THEN 'ARRAY'
              WHEN nt.nspname = 'pg_catalog' THEN format_type(a.atttypid, NULL)
              ELSE 'USER-DEFINED' END
      END AS raw_data_type
) dt
LEFT OUTER JOIN (
VALUES
 ('character varying', 'varchar'),
 ('character', 'char'),
 ('double precision', 'float8')
) AS type_map(src, dst)
  ON (type_map.src = dt.raw_data_type)
WHERE
a.attnum > 0
AND NOT a.attisdropped
AND c.relkind IN ('r', 'v', 'f', 'p', 't', 'm')
AND c.oid = @table_oid
ORDER BY
 a.attnum;";
    internal static async IAsyncEnumerable<PgColumn> ListColumnsAsync(PgCatalog catalog, uint tableOid, [EnumeratorCancellation] CancellationToken ct = default)
    {
        ct.ThrowIfCancellationRequested();
        var sqlSet = GenerateSQLSet();
        sqlSet["table_oid"]!.Value = tableOid;

        var q = catalog.Session.CreateQuery();
        await foreach (var result in q.StreamAsync<PgColumn, PgCatalog>(catalog, sqlSet.SQL, sqlSet.Parameters, ct).ConfigureAwait(false))
        {
            yield return result;
        }
    }
}
